local gp = require("gp")

gp.setup({
  openai_api_key = os.getenv("OPENAI_API_KEY"),
})

require("which-key").add({
    -- VISUAL mode mappings
    -- s, x, v modes are handled the same way by which_key
    {
        mode = { "v" },
        nowait = true,
        remap = false,
        { "<C-q><C-t>", ":<C-u>'<,'>GpChatNew tabnew<cr>", desc = "ChatNew tabnew" },
        { "<C-q><C-v>", ":<C-u>'<,'>GpChatNew vsplit<cr>", desc = "ChatNew vsplit" },
        { "<C-q><C-x>", ":<C-u>'<,'>GpChatNew split<cr>", desc = "ChatNew split" },
        { "<C-q>a", ":<C-u>'<,'>GpAppend<cr>", desc = "Visual Append (after)" },
        { "<C-q>b", ":<C-u>'<,'>GpPrepend<cr>", desc = "Visual Prepend (before)" },
        { "<C-q>c", ":<C-u>'<,'>GpChatNew<cr>", desc = "Visual Chat New" },
        { "<C-q>g", group = "generate into new .." },
        { "<C-q>ge", ":<C-u>'<,'>GpEnew<cr>", desc = "Visual GpEnew" },
        { "<C-q>gn", ":<C-u>'<,'>GpNew<cr>", desc = "Visual GpNew" },
        { "<C-q>gp", ":<C-u>'<,'>GpPopup<cr>", desc = "Visual Popup" },
        { "<C-q>gt", ":<C-u>'<,'>GpTabnew<cr>", desc = "Visual GpTabnew" },
        { "<C-q>gv", ":<C-u>'<,'>GpVnew<cr>", desc = "Visual GpVnew" },
        { "<C-q>i", ":<C-u>'<,'>GpImplement<cr>", desc = "Implement selection" },
        { "<C-q>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent" },
        { "<C-q>p", ":<C-u>'<,'>GpChatPaste<cr>", desc = "Visual Chat Paste" },
        { "<C-q>r", ":<C-u>'<,'>GpRewrite<cr>", desc = "Visual Rewrite" },
        { "<C-q>s", "<cmd>GpStop<cr>", desc = "GpStop" },
        { "<C-q>t", ":<C-u>'<,'>GpChatToggle<cr>", desc = "Visual Toggle Chat" },
        { "<C-q>w", group = "Whisper" },
        { "<C-q>wa", ":<C-u>'<,'>GpWhisperAppend<cr>", desc = "Whisper Append" },
        { "<C-q>wb", ":<C-u>'<,'>GpWhisperPrepend<cr>", desc = "Whisper Prepend" },
        { "<C-q>we", ":<C-u>'<,'>GpWhisperEnew<cr>", desc = "Whisper Enew" },
        { "<C-q>wn", ":<C-u>'<,'>GpWhisperNew<cr>", desc = "Whisper New" },
        { "<C-q>wp", ":<C-u>'<,'>GpWhisperPopup<cr>", desc = "Whisper Popup" },
        { "<C-q>wr", ":<C-u>'<,'>GpWhisperRewrite<cr>", desc = "Whisper Rewrite" },
        { "<C-q>wt", ":<C-u>'<,'>GpWhisperTabnew<cr>", desc = "Whisper Tabnew" },
        { "<C-q>wv", ":<C-u>'<,'>GpWhisperVnew<cr>", desc = "Whisper Vnew" },
        { "<C-q>ww", ":<C-u>'<,'>GpWhisper<cr>", desc = "Whisper" },
        { "<C-q>x", ":<C-u>'<,'>GpContext<cr>", desc = "Visual GpContext" },
    },

    -- NORMAL mode mappings
    {
        mode = { "n" },
        nowait = true,
        remap = false,
        { "<C-q><C-t>", "<cmd>GpChatNew tabnew<cr>", desc = "New Chat tabnew" },
        { "<C-q><C-v>", "<cmd>GpChatNew vsplit<cr>", desc = "New Chat vsplit" },
        { "<C-q><C-x>", "<cmd>GpChatNew split<cr>", desc = "New Chat split" },
        { "<C-q>a", "<cmd>GpAppend<cr>", desc = "Append (after)" },
        { "<C-q>b", "<cmd>GpPrepend<cr>", desc = "Prepend (before)" },
        { "<C-q>c", "<cmd>GpChatNew<cr>", desc = "New Chat" },
        { "<C-q>f", "<cmd>GpChatFinder<cr>", desc = "Chat Finder" },
        { "<C-q>g", group = "generate into new .." },
        { "<C-q>ge", "<cmd>GpEnew<cr>", desc = "GpEnew" },
        { "<C-q>gn", "<cmd>GpNew<cr>", desc = "GpNew" },
        { "<C-q>gp", "<cmd>GpPopup<cr>", desc = "Popup" },
        { "<C-q>gt", "<cmd>GpTabnew<cr>", desc = "GpTabnew" },
        { "<C-q>gv", "<cmd>GpVnew<cr>", desc = "GpVnew" },
        { "<C-q>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent" },
        { "<C-q>r", "<cmd>GpRewrite<cr>", desc = "Inline Rewrite" },
        { "<C-q>s", "<cmd>GpStop<cr>", desc = "GpStop" },
        { "<C-q>t", "<cmd>GpChatToggle<cr>", desc = "Toggle Chat" },
        { "<C-q>w", group = "Whisper" },
        { "<C-q>wa", "<cmd>GpWhisperAppend<cr>", desc = "Whisper Append (after)" },
        { "<C-q>wb", "<cmd>GpWhisperPrepend<cr>", desc = "Whisper Prepend (before)" },
        { "<C-q>we", "<cmd>GpWhisperEnew<cr>", desc = "Whisper Enew" },
        { "<C-q>wn", "<cmd>GpWhisperNew<cr>", desc = "Whisper New" },
        { "<C-q>wp", "<cmd>GpWhisperPopup<cr>", desc = "Whisper Popup" },
        { "<C-q>wr", "<cmd>GpWhisperRewrite<cr>", desc = "Whisper Inline Rewrite" },
        { "<C-q>wt", "<cmd>GpWhisperTabnew<cr>", desc = "Whisper Tabnew" },
        { "<C-q>wv", "<cmd>GpWhisperVnew<cr>", desc = "Whisper Vnew" },
        { "<C-q>ww", "<cmd>GpWhisper<cr>", desc = "Whisper" },
        { "<C-q>x", "<cmd>GpContext<cr>", desc = "Toggle GpContext" },
    },

    -- INSERT mode mappings
    {
        mode = { "i" },
        nowait = true,
        remap = false,
        { "<C-q><C-t>", "<cmd>GpChatNew tabnew<cr>", desc = "New Chat tabnew" },
        { "<C-q><C-v>", "<cmd>GpChatNew vsplit<cr>", desc = "New Chat vsplit" },
        { "<C-q><C-x>", "<cmd>GpChatNew split<cr>", desc = "New Chat split" },
        { "<C-q>a", "<cmd>GpAppend<cr>", desc = "Append (after)" },
        { "<C-q>b", "<cmd>GpPrepend<cr>", desc = "Prepend (before)" },
        { "<C-q>c", "<cmd>GpChatNew<cr>", desc = "New Chat" },
        { "<C-q>f", "<cmd>GpChatFinder<cr>", desc = "Chat Finder" },
        { "<C-q>g", group = "generate into new .." },
        { "<C-q>ge", "<cmd>GpEnew<cr>", desc = "GpEnew" },
        { "<C-q>gn", "<cmd>GpNew<cr>", desc = "GpNew" },
        { "<C-q>gp", "<cmd>GpPopup<cr>", desc = "Popup" },
        { "<C-q>gt", "<cmd>GpTabnew<cr>", desc = "GpTabnew" },
        { "<C-q>gv", "<cmd>GpVnew<cr>", desc = "GpVnew" },
        { "<C-q>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent" },
        { "<C-q>r", "<cmd>GpRewrite<cr>", desc = "Inline Rewrite" },
        { "<C-q>s", "<cmd>GpStop<cr>", desc = "GpStop" },
        { "<C-q>t", "<cmd>GpChatToggle<cr>", desc = "Toggle Chat" },
        { "<C-q>w", group = "Whisper" },
        { "<C-q>wa", "<cmd>GpWhisperAppend<cr>", desc = "Whisper Append (after)" },
        { "<C-q>wb", "<cmd>GpWhisperPrepend<cr>", desc = "Whisper Prepend (before)" },
        { "<C-q>we", "<cmd>GpWhisperEnew<cr>", desc = "Whisper Enew" },
        { "<C-q>wn", "<cmd>GpWhisperNew<cr>", desc = "Whisper New" },
        { "<C-q>wp", "<cmd>GpWhisperPopup<cr>", desc = "Whisper Popup" },
        { "<C-q>wr", "<cmd>GpWhisperRewrite<cr>", desc = "Whisper Inline Rewrite" },
        { "<C-q>wt", "<cmd>GpWhisperTabnew<cr>", desc = "Whisper Tabnew" },
        { "<C-q>wv", "<cmd>GpWhisperVnew<cr>", desc = "Whisper Vnew" },
        { "<C-q>ww", "<cmd>GpWhisper<cr>", desc = "Whisper" },
        { "<C-q>x", "<cmd>GpContext<cr>", desc = "Toggle GpContext" },
    },
})
