session_name: WebKit${WS}
start_directory: "/Users/marcusplutowski/Devel/WebKit/${WS}/OpenSource/"
windows:
- window_name: IDE
  focus: 'true'
  layout: f023,465x124,0,0{85x124,0,0[85x63,0,0,26,85x30,0,64,27,85x29,0,95,28],379x124,86,0[379x94,86,0,29,379x29,86,95{167x29,86,95,30,211x29,254,95,31}]}
  options: {}
  panes:
  - btop
  - shell_command: watch -c -n 2 time git -c color.status=always status -uno
    start_directory: "/Users/marcusplutowski/Devel/WebKit/${WS}/OpenSource/"
  - shell_command: watch -c -n 3 time git -c color.status=always status -uno
    start_directory: "/Users/marcusplutowski/Devel/WebKit/${WS}/Internal/"
  - shell_command: nvim
    focus: 'true'
  - zsh
  - zsh
- window_name: Aux
  layout: main-horizontal
  panes:
  - shell_command: zsh
    focus: 'true'
  - start_command: zsh
    start_directory: "/Users/marcusplutowski/Devel/WebKit/${WS}/OpenSource/PerformanceTests/JetStream2/"
  - zsh
  - zsh
