return {
  { "robitx/gp.nvim",
    cmd = {
      "GpChatNew", "GpChatToggle", "GpChatFinder",
      "GpRewrite", "GpAppend", "GpPrepend",
      "GpNew", "GpEnew", "GpVnew", "GpTabnew", "GpPopup",
      "GpNextAgent", "GpStop", "GpContext",
      "GpWhisper", "GpWhisperRewrite", "GpWhisperAppend", "GpWhisperPrepend",
      "GpImplement",
    },
    keys = {
      -- Normal mode
      { "<C-q>c", "<cmd>GpChatNew<cr>", mode = "n", desc = "New Chat" },
      { "<C-q>t", "<cmd>GpChatToggle<cr>", mode = "n", desc = "Toggle Chat" },
      { "<C-q>f", "<cmd>GpChatFinder<cr>", mode = "n", desc = "Chat Finder" },
      { "<C-q>r", "<cmd>GpRewrite<cr>", mode = "n", desc = "Inline Rewrite" },
      { "<C-q>a", "<cmd>GpAppend<cr>", mode = "n", desc = "Append (after)" },
      { "<C-q>b", "<cmd>GpPrepend<cr>", mode = "n", desc = "Prepend (before)" },
      { "<C-q>n", "<cmd>GpNextAgent<cr>", mode = "n", desc = "Next Agent" },
      { "<C-q>s", "<cmd>GpStop<cr>", mode = "n", desc = "GpStop" },
      { "<C-q>x", "<cmd>GpContext<cr>", mode = "n", desc = "Toggle GpContext" },
      -- Visual mode
      { "<C-q>c", ":<C-u>'<,'>GpChatNew<cr>", mode = "v", desc = "Visual Chat New" },
      { "<C-q>t", ":<C-u>'<,'>GpChatToggle<cr>", mode = "v", desc = "Visual Toggle Chat" },
      { "<C-q>r", ":<C-u>'<,'>GpRewrite<cr>", mode = "v", desc = "Visual Rewrite" },
      { "<C-q>a", ":<C-u>'<,'>GpAppend<cr>", mode = "v", desc = "Visual Append (after)" },
      { "<C-q>b", ":<C-u>'<,'>GpPrepend<cr>", mode = "v", desc = "Visual Prepend (before)" },
      { "<C-q>i", ":<C-u>'<,'>GpImplement<cr>", mode = "v", desc = "Implement selection" },
      { "<C-q>p", ":<C-u>'<,'>GpChatPaste<cr>", mode = "v", desc = "Visual Chat Paste" },
    },
    config = function()
      require("gp").setup({
        openai_api_key = os.getenv("OPENAI_API_KEY"),
      })

      -- Register remaining which-key groups for gp.nvim
      local ok, which_key = pcall(require, "which-key")
      if ok then
        which_key.add({
          -- VISUAL mode
          {
            mode = { "v" },
            nowait = true,
            remap = false,
            { "<C-q><C-t>", ":<C-u>'<,'>GpChatNew tabnew<cr>", desc = "ChatNew tabnew" },
            { "<C-q><C-v>", ":<C-u>'<,'>GpChatNew vsplit<cr>", desc = "ChatNew vsplit" },
            { "<C-q><C-x>", ":<C-u>'<,'>GpChatNew split<cr>", desc = "ChatNew split" },
            { "<C-q>g", group = "generate into new .." },
            { "<C-q>ge", ":<C-u>'<,'>GpEnew<cr>", desc = "Visual GpEnew" },
            { "<C-q>gn", ":<C-u>'<,'>GpNew<cr>", desc = "Visual GpNew" },
            { "<C-q>gp", ":<C-u>'<,'>GpPopup<cr>", desc = "Visual Popup" },
            { "<C-q>gt", ":<C-u>'<,'>GpTabnew<cr>", desc = "Visual GpTabnew" },
            { "<C-q>gv", ":<C-u>'<,'>GpVnew<cr>", desc = "Visual GpVnew" },
            { "<C-q>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent" },
            { "<C-q>s", "<cmd>GpStop<cr>", desc = "GpStop" },
            { "<C-q>w", group = "Whisper" },
            { "<C-q>wa", ":<C-u>'<,'>GpWhisperAppend<cr>", desc = "Whisper Append" },
            { "<C-q>wb", ":<C-u>'<,'>GpWhisperPrepend<cr>", desc = "Whisper Prepend" },
            { "<C-q>we", ":<C-u>'<,'>GpWhisperEnew<cr>", desc = "Whisper Enew" },
            { "<C-q>wn", ":<C-u>'<,'>GpWhisperNew<cr>", desc = "Whisper New" },
            { "<C-q>wp", ":<C-u>'<,'>GpWhisperPopup<cr>", desc = "Whisper Popup" },
            { "<C-q>wr", ":<C-u>'<,'>GpWhisperRewrite<cr>", desc = "Whisper Rewrite" },
            { "<C-q>wt", ":<C-u>'<,'>GpWhisperTabnew<cr>", desc = "Whisper Tabnew" },
            { "<C-q>wv", ":<C-u>'<,'>GpWhisperVnew<cr>", desc = "Whisper Vnew" },
            { "<C-q>ww", ":<C-u>'<,'>GpWhisper<cr>", desc = "Whisper" },
            { "<C-q>x", ":<C-u>'<,'>GpContext<cr>", desc = "Visual GpContext" },
          },
          -- NORMAL mode (additional bindings not covered by keys)
          {
            mode = { "n" },
            nowait = true,
            remap = false,
            { "<C-q><C-t>", "<cmd>GpChatNew tabnew<cr>", desc = "New Chat tabnew" },
            { "<C-q><C-v>", "<cmd>GpChatNew vsplit<cr>", desc = "New Chat vsplit" },
            { "<C-q><C-x>", "<cmd>GpChatNew split<cr>", desc = "New Chat split" },
            { "<C-q>g", group = "generate into new .." },
            { "<C-q>ge", "<cmd>GpEnew<cr>", desc = "GpEnew" },
            { "<C-q>gn", "<cmd>GpNew<cr>", desc = "GpNew" },
            { "<C-q>gp", "<cmd>GpPopup<cr>", desc = "Popup" },
            { "<C-q>gt", "<cmd>GpTabnew<cr>", desc = "GpTabnew" },
            { "<C-q>gv", "<cmd>GpVnew<cr>", desc = "GpVnew" },
            { "<C-q>w", group = "Whisper" },
            { "<C-q>wa", "<cmd>GpWhisperAppend<cr>", desc = "Whisper Append (after)" },
            { "<C-q>wb", "<cmd>GpWhisperPrepend<cr>", desc = "Whisper Prepend (before)" },
            { "<C-q>we", "<cmd>GpWhisperEnew<cr>", desc = "Whisper Enew" },
            { "<C-q>wn", "<cmd>GpWhisperNew<cr>", desc = "Whisper New" },
            { "<C-q>wp", "<cmd>GpWhisperPopup<cr>", desc = "Whisper Popup" },
            { "<C-q>wr", "<cmd>GpWhisperRewrite<cr>", desc = "Whisper Inline Rewrite" },
            { "<C-q>wt", "<cmd>GpWhisperTabnew<cr>", desc = "Whisper Tabnew" },
            { "<C-q>wv", "<cmd>GpWhisperVnew<cr>", desc = "Whisper Vnew" },
            { "<C-q>ww", "<cmd>GpWhisper<cr>", desc = "Whisper" },
          },
          -- INSERT mode
          {
            mode = { "i" },
            nowait = true,
            remap = false,
            { "<C-q><C-t>", "<cmd>GpChatNew tabnew<cr>", desc = "New Chat tabnew" },
            { "<C-q><C-v>", "<cmd>GpChatNew vsplit<cr>", desc = "New Chat vsplit" },
            { "<C-q><C-x>", "<cmd>GpChatNew split<cr>", desc = "New Chat split" },
            { "<C-q>a", "<cmd>GpAppend<cr>", desc = "Append (after)" },
            { "<C-q>b", "<cmd>GpPrepend<cr>", desc = "Prepend (before)" },
            { "<C-q>c", "<cmd>GpChatNew<cr>", desc = "New Chat" },
            { "<C-q>f", "<cmd>GpChatFinder<cr>", desc = "Chat Finder" },
            { "<C-q>g", group = "generate into new .." },
            { "<C-q>ge", "<cmd>GpEnew<cr>", desc = "GpEnew" },
            { "<C-q>gn", "<cmd>GpNew<cr>", desc = "GpNew" },
            { "<C-q>gp", "<cmd>GpPopup<cr>", desc = "Popup" },
            { "<C-q>gt", "<cmd>GpTabnew<cr>", desc = "GpTabnew" },
            { "<C-q>gv", "<cmd>GpVnew<cr>", desc = "GpVnew" },
            { "<C-q>n", "<cmd>GpNextAgent<cr>", desc = "Next Agent" },
            { "<C-q>r", "<cmd>GpRewrite<cr>", desc = "Inline Rewrite" },
            { "<C-q>s", "<cmd>GpStop<cr>", desc = "GpStop" },
            { "<C-q>t", "<cmd>GpChatToggle<cr>", desc = "Toggle Chat" },
            { "<C-q>w", group = "Whisper" },
            { "<C-q>wa", "<cmd>GpWhisperAppend<cr>", desc = "Whisper Append (after)" },
            { "<C-q>wb", "<cmd>GpWhisperPrepend<cr>", desc = "Whisper Prepend (before)" },
            { "<C-q>we", "<cmd>GpWhisperEnew<cr>", desc = "Whisper Enew" },
            { "<C-q>wn", "<cmd>GpWhisperNew<cr>", desc = "Whisper New" },
            { "<C-q>wp", "<cmd>GpWhisperPopup<cr>", desc = "Whisper Popup" },
            { "<C-q>wr", "<cmd>GpWhisperRewrite<cr>", desc = "Whisper Inline Rewrite" },
            { "<C-q>wt", "<cmd>GpWhisperTabnew<cr>", desc = "Whisper Tabnew" },
            { "<C-q>wv", "<cmd>GpWhisperVnew<cr>", desc = "Whisper Vnew" },
            { "<C-q>ww", "<cmd>GpWhisper<cr>", desc = "Whisper" },
            { "<C-q>x", "<cmd>GpContext<cr>", desc = "Toggle GpContext" },
          },
        })
      end
    end,
  },
}
